version: '3.4'

services:
  confighost:
    image: ${DOCKER_REGISTRY}confighost
    build:
      context: .
      dockerfile: Services/Config/ConfigHost/Dockerfile

  config.webmvc:
    image: ${DOCKER_REGISTRY}configwebmvc
    build:
      context: .
      dockerfile: Web/Config/Config.WebMVC/Dockerfile

